version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .docker/php82/Dockerfile
    image: php82-collection
    container_name: php-collection
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
