name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests with PHP${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        include:
          - php: 8.0
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage results to Coveralls
        if: matrix.analysis
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls -n -W
          vendor/bin/php-coveralls --coverage_clover=clover.xml -v