version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php82-collection
    container_name: php-collection
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../../:/var/www
    networks:
      - default

networks:
  default:
    name: php-collection
